name: Linux

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DISPLAY: :0
    steps:

    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install ninja-build -y
        sudo apt-get install libwayland-dev
        sudo apt install libxkbcommon-dev
        sudo apt install xorg-dev
        sudo apt-get install -y xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0
        sudo /usr/bin/Xvfb $DISPLAY -screen 0 1280x1024x24 &

    - name: build GLFW
      run: |
        cd vendor/GLFW
        cmake . -G "Ninja"
        ninja
        mv src/libglfw3.a ../../lib/libglfw3.a

    - name: build
      run: make

    - name: test
      run: make test

    - name: clean
      run: make clean
