name: Linux

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install dependencies
      run: |
        sudo apt-get install ninja-build -y
        sudo apt-get install xorg-dev
        sudo apt-get install freeglut3-dev

    - name: build
      run: make

    - name: clean
      run: make clean
