name: Linux

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libwayland-dev
        sudo apt install libxkbcommon-dev
        sudo apt install xorg-dev

    - name: build GLFW
      run: |
        cd vendor/GLFW
        cmake .
        ninja
        mv src/libglfw3.a ../../lib/libglfw3.a

    - name: build
      run: make

    - name: clean
      run: make clean
