name: Linux

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: install dependencies
      run: |
        sudo apt-get install libgl-dev
        sudo apt-get install libgdiplus

    - name: build
      run: make

    - name: clean
      run: make clean
