name: OSX

on: [push, pull_request]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1

    - name: install dependencies
      run: brew install ninja

    - name: build
      run: make

    - name: clean
      run: make clean
